### ISSUE TITLE
Openocd fails to open after first time running it

### ISSUE THREAD

**Issue by salmansheikh** [RISCV-on-Microsemi-FPGA/SoftConsole#16]
I took the miv-rv32im-systick-blinky/main.c and modified one print statement, recompiled and tried to restart the openocd and it failed with this message.  

GNU MCU Eclipse (Microsemi SoftConsole build) 64-bits Open On-Chip Debugger 0.10.0+dev-00084-gae68d7da-dirty (2018-06-28-11:40)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
adapter speed: 6000 kHz
trst_only separate trst_push_pull
do_board_reset_init
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections

'' does not match any available port
fpServer: recv() function call failed with a SOCKET_ERROR

![code1](https://user-images.githubusercontent.com/3300400/46766823-2bbec380-ccb1-11e8-84e4-56a357fd9832.png)

**Comment by AntonKrug** [comment]
Looks like your FlashPro Programmer was not detected. If you it was never working for you, go through the release notes as there are listed essential installation steps and FAQ for common problems. If it was working at first and then stopped working then check if you have already running Debug session and the FlashPro you have is already taken. Is the programmer present in the Device manager (assuming you are running Windows and not Linux with Windows styling), just to make sure check the USB connection to the programmer (unplug it fully to be sure). If my assumption is wrong and you are using Linux then go through the release notes as there are required steps needed for the flashpro to work.

**Comment by salmansheikh** [comment]
Okay, it was working and programmed one time prior to this error. I will try reprogramming it again.

**Comment by AntonKrug** [comment]
Does the Device manager show the FlashPro ports properly?

**Comment by PratikAher20** [comment]
Hii @salmansheikh Did you got the solution for this issue? I am also facing some similar issue as "fpClient: recv() function from fpServer API failed, error 10054". Can you please help me to solve this issue?

**Comment by salmansheikh** [comment]
Sorry  Pratik.  This was 5+ years  ago and that project  is no longer funded.  I don't remember if i got past that error.

**Comment by aakash-mchp** [comment]
Hi @PratikAher20,
This page and repository are no longer supported, the projects have been moved to a new organization. https://github.com/Mi-V-Soft-RISC-V is the new page for RISC-V Soft IP processors on Microchip (formerly Microsemi) FPGAs.
The projects and designs have been improved and updated quite a bit in the past years, for the same same systick-blinky project you can follow this link: https://github.com/Mi-V-Soft-RISC-V/miv-rv32-bare-metal-examples/tree/main/driver-examples/miv-rv32-hal/miv-rv32i-systick-blinky.
Please add a comment for any further clarity needed.
