### ISSUE TITLE
Problem with Floating point multiplication

### ISSUE THREAD

**Issue by BhuvaHiren** [RISCV-on-Microsemi-FPGA/SoftConsole#20]
I am facing an issue  when i try floating point multiplication. 
I get expected value when i use.
ambient_temp =  (uint16_t) ( ( avg_ptat  * 0.0585074 ) + 1041.17 );

But, when we try using below it is not working as expected.

gradient_ptat  = 0x3D6fa564;
ptat_offset = 0x44822561;
ambient_temp =  (uint16_t)( ( avg_ptat  * gradient_ptat ) + ptat_offset ) ;

**Comment by AntonKrug** [comment]
Hi @BhuvaHiren 
Can you post the exact types of the gradient_ptat, ptat_offset, ambient_temp?

Do you try to save these as raw IEEE 754 representations? It does look like you do, as the 0x3D6fa564 is exactly the 0.0585074 

But I don't think the code will work that way, what you have done is to just save it as literal number (it doesn't care you wrote it as hex) and you could have been assigning gradient_ptat = 1030727012;

I think the steps below are necessary to make sure the raw value will be treated as IEEE 754:

- by giving it the raw value (hex/dec doesn't matter)
- create a pointer to it
- then cast that pointer to a pointer pointing to a float type (sorry for this sentence)
- and as last derefence that floating pointer

You can do it like this:
```
uint32_t gradient_ptat_raw = 0x3D6fa564;
float gradient_ptat = *(float *) &gradient_ptat_raw;
```
But you can simplify it, then you can make it into a macro or function and force inline optimalisations on that function.

**Comment by AntonKrug** [comment]
Similar steps can be applied for getting the raw IEEE 754 representation of a float variable. And they can be written as one-liners.

**Comment by BhuvaHiren** [comment]
Thanks @AntonKrug ,
I am able to get the expected results after this steps.

**Comment by AntonKrug** [comment]
@BhuvaHiren That is great, if you are happy then you can close the issue?

I forgot to ask, just from curiosity why you needed this? I could think of 2 instances. 

- I know that for some edge cases where it needs to be guaranteed that the intended value must be kept, like subnormal values, signed infinities, signed zeroes etc... While the number you are using looks to be perfectly generic and using 0.0585074f should perfectly create that raw representation.

- Or when the values are transmitted over a network/serial protocols then they need to be serialised and parsed. If that is the case then it's perfect solution for it.

But if you had some other issues and this is only workaround, maybe it would be better to address the issue directly. For example you mention the floating point values without postfix "f" which could imply double which then might get converted into single floating point, some cores might have only single floating point as hardfloat which means then the double is a software implementation which bumps the size etc... If it's something awkward like that, then make your all floating points into a specific single floating point by postfixing "f" and you might not need to convert it from the raw values.

**Comment by BhuvaHiren** [comment]
@AntonKrug,
I am getting this value from the sensor connected on SPI.  So, the solution works for me. 
I am closing the issue as it is resolved.
Thanks.
