### ISSUE TITLE
Unable to get external interrupt connected on 24 number

### ISSUE THREAD

**Issue by BhuvaHiren** [RISCV-on-Microsemi-FPGA/SoftConsole#21]
I am not getting interrupt connected to PCIE_1_INTERRUPT_OUT.
We tried by connecting led with this pin. The led shows that the interrupt are being triggered as it gets turned on but my interrupt handler function is not being called.
Below are the APIs I am calling to configure the interrupt.
  
PLIC_init();
PLIC_SetPriority(External_24_IRQn, 1);
PLIC_EnableIRQ(External_24_IRQn);
HAL_enable_interrupts();

And I am expecting this API to be called when interrupt is triggered.
uint8_t External_24_IRQHandler(void);

Please Let, me know if I am missing anything.

**Comment by AntonKrug** [comment]
Hi @BhuvaHiren 

- what design you are using, how are the IRQs configured there?
- can you try and use 23 instead of 24, does it have some effect on the result?
- could you make a breakpoint in the **static void handle_m_ext_interrupt(void)** and check what values is the **int_num**?
- can you read the value of this uint32 ? PLIC->TARGET_ENABLES[0].ENABLES[0] to see if it's still enabled later on (one bit for each interrupt).

Anton

**Comment by BhuvaHiren** [comment]
Hi @AntonKrug,
 
Thanks for reply.

We are using our custom PCie end point design. for which the interrupt pin of the PCIe is connected with external interrupt 24.
So, We need to use External_25_IRQn instead External_24_IRQn.
After trying this we are getting the interrupt.

**Comment by AntonKrug** [comment]
It is odd, I would like to follow this up internally, could you tell me on what base design is your design based upon? Are you using our Mi-V cores? If yes, which one?

**Comment by BhuvaHiren** [comment]
I read the comments in hw_platform.h(line 70-74) of the miv-rv32im-systick-blinky project. So, According to it, pin IRQ[24] should be mapped to External_25_IRQn.

**Comment by AntonKrug** [comment]
Oh, now I'm getting it, you were not considering the offset by 1.

**Comment by BhuvaHiren** [comment]
Yeah, That's true.

**Comment by AntonKrug** [comment]
I will look into the examples if we can make this more obvious in the example code to avoid confusing users in the future.
